services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite_gourmand_app
    ports:
      - "8080:80"
    environment:
      APP_ENV: dev
      APP_SECRET: docker_local_secret
      DATABASE_URL: "mysql://vite_user:vite_password@database:3306/vite_gourmand?serverVersion=8.0.36&charset=utf8mb4"
      MAILER_DSN: "smtp://mailer:1025"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/var
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.0
    container_name: vite_gourmand_database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: vite_gourmand
      MYSQL_USER: vite_user
      MYSQL_PASSWORD: vite_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-proot_password"
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  mailer:
    image: axllent/mailpit
    container_name: vite_gourmand_mailer
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  database_data: